### ISSUE TITLE
Biaxial with BarChart is not right

### ISSUE THREAD

**Issue by wulucxy** [jamestthompson3/viiksetjs#4]
awesome project!

I have a question，when i change `examples/src/components/Biaxial.js`:

```javascript
<BarChart color="rgb(244, 196, 65)" dataKey="posts" axisId="posts" />
 <LineChart color="rgb(238, 66, 244)" dataKey="users" axisId="users" />
```

and the BarItem is not right as below:

![image](https://user-images.githubusercontent.com/5326403/45729966-b2780780-bc01-11e8-935a-61e0f86ce946.png)

maybe calcuation of Bar is not right?

**Comment by jamestthompson3** [comment]
Thanks for reporting the issue @wulucxy ! It should be fixed now.

**Comment by wulucxy** [comment]
@jamestthompson3 I use the newest version of code，but this problem is still exist。

normally the Bar height is according to the right axis。but it still looks like before。

PS: I use the `npm link` strategy in the `example` fold

**Comment by jamestthompson3** [comment]
@wulucxy  You are right. It wasn't correctly fixed. It's also bad DX on my part not telling you to use `npm link` to run the examples folder. [This commit](https://github.com/jamestthompson3/viiksetjs/commit/45e1f76bf2fab1bb19ee2782f495034c35f10b28) should fix both.
